### ISSUE TITLE
Luhn algorithm calculated in reverse

### ISSUE THREAD

**Issue by troyfigiel** [codeperfectplus/Sanatio#10]
When looking at the definition of `LuhnAlgorithm`, I noticed the multiplication of digits in the number by the alternating pattern of 2 and 1 starts from the left. The Luhn algorithm actually starts this multiplication from the right instead. Since the test case has an odd length (excluding the checksum digit), it does not capture this difference. For example, 109 should be valid, but instead `LuhnAlgorithm("108").verify()` returns `True`. This can be fixed by replacing `remaining_numbers` by `reversed(remaining_numbers)` in the implementation.

**Comment by codeperfectplus** [comment]
You're right, Great catch! This fix would address the issue and make the LuhnAlgorithm function accurate for both even and odd-length numbers. Do you want to create PR ?
