### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by yoursmanjunad** [codeperfectplus/Sanatio#4]
I believe making a application containerized with docker, can really helps you to scale this further with large infrastructure or just simply download this image from the repository to run on any device instead of cloning the repo or sharing the code files. This looks more professional, compact, portable and easy to run ( on any device). I can help you with making it containerized with Docker and also other CI/CD helping terms like Jenkinsfile, Ansible Playbooks etc.

**Comment by codeperfectplus** [comment]
I am distributing it as a pip package, so I don't think containerization will be helpful. CI/CD may be helpful.
